# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


destination: docs/
host: localhost
livereload: true
# show_drafts: true

paginate: 6
paginate_path: "blog/:num/"
permalink: :slug/

sass:
  sass_dir: assets/sass
  style: compressed

title: Monjibram
email: benji@monjibram.com
tagline: Benji makes your website better.
description: >- # this means to ignore newlines until "author:"
  Benjamin Kostenbader is Front-End Developer at Top Hat. He is also a proud father, cyclist, and squash enthusiast.
author: Benjamin Kostenbader
name: Benjamin Kostenbader
logo: assets/images/Benji.jpg
social:
  links:
    linkedin: https://www.linkedin.com/in/benjamin-kostenbader-18499836/
    facebook: https://www.facebook.com/THEimmortal
    codepen: https://codepen.io/benjithaimmortal
    github: https://github.com/benjithaimmortal
    twitter: https://twitter.com/monjibram
google_site_verification: OTG5c_uywRHQgQpvdcwgCYY02h8ofndgJq_kGPt1l_I
# google_site_verification: google-site-verification=OTG5c_uywRHQgQpvdcwgCYY02h8ofndgJq_kGPt1l_I
lang: en_US


# collections:
#   projects:
#     output: true
#     img:    true
#     title:  true
#     date:   true
#     layout: true




defaults:
  # -
  #   scope:
  #     path: ""
  #     type: "projects"
  #   values:
  #     layout: project
  #     img: /assets/images/Hoi_An_Vietnam.jpg
  #     title: A New, Default Place
  #     date: "2020-06-11"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Benji
      hero: pages.jpg
      image: assets/images/pages.jpg
  -
    scope:
      path: ""
      type: pages
    values:
      layout: base
      image: assets/images/Benji.jpg
      author: Benji
  -
    scope:
      path: assets/*
    values:
      sitemap: false
  -
    scope:
      path: docs/*
    values:
      sitemap: false




baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.monjibram.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://www.monjibram.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  benjithaimmortal

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
